# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UF' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UF
  pod 'Firebase/Core'
  platform :ios, '11.0'

  target 'UFTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
